### ISSUE TITLE
name a release after the amazing RMS

### ISSUE THREAD

**Issue by robbyoconnor** [illacceptanything/illacceptanything#255]

**Comment by huei90** [comment]
what is RMS

**Comment by GLolol** [comment]
I will do this when the project is finalized sometime in 2059.

**Comment by ashelly** [comment]
>  what is RMS

RMS is a statistical measure defined as the square root of the mean of the squares of a sample.  It campaigns for software to be distributed in a manner such that its users receive the freedoms to use, study, distribute and modify that software. During the 1999-00 school year, RMS was recognized with the Blue Ribbon School Award of Excellence by the United States Department of Education.  In addition to this, RMS is pursuing an initiative to encourage young microscope users who may go on to influence microscopy in the future. [*](https://en.wikipedia.org/wiki/RMS)
