### ISSUE TITLE
Get the the “trending” page

### ISSUE THREAD

**Issue by ProgVal** [illacceptanything/illacceptanything#384]
Still not [here](https://github.com/trending)?

**Comment by GLolol** [comment]
[We made it, woo!](https://github.com/trending) - Wed Apr  8 17:24:58 PDT 2015

**Comment by ProgVal** [comment]
Still not in first position [here](https://github.com/trending?since=weekly)?

**Comment by GLolol** [comment]
It hasn't been a week yet.

**Comment by ProgVal** [comment]
So what? It's possible to be at the top without waiting for the end of the week.

**Comment by MiLk** [comment]
![2015-04-10-221259_1060x796_scrot](https://cloud.githubusercontent.com/assets/29782/7088478/d13120fc-dfce-11e4-810d-57c37f518399.png)
![2015-04-10-221321_1032x905_scrot](https://cloud.githubusercontent.com/assets/29782/7088479/d13564e6-dfce-11e4-9650-2c8d80de7501.png)
