### ISSUE TITLE
Feature request: accept pull requests that are not created or submitted

### ISSUE THREAD

**Issue by joeatwork** [illacceptanything/illacceptanything#42]
This is an exciting project! I'd like to suggest a feature- while the project currently accepts all pull requests submitted, what about those pull requests that _aren't_ submitted? For example, there must be thousands of pull requests right now that won't ever be merged, simply because they're for other projects with disjoint commit histories? 

If you wanted to get really ambitious, you could even support pull requests that are never submitted or created at all- what about the commits associated with this feature request, for example, that I have no intention of ever writing, much less submitting to a project on Github?

**Comment by DanielHenneberger** [comment]
This should also apply to alternative realities where our alternative selves did submit pull requests. Additionally, there could be unrealized realities where our pull requests did get accepted but never materialized.

**Comment by GLolol** [comment]
Why limit ourselves to commits? We should be able to truly include **anything**, just like the repository name says! Physical objects, abstract ideas, everything known in the finite and infinite universes!

I would like to include the following as examples:
- A Jeep
- A dog
- Mount Everest
- Schroedinger's cat
- This repository itself.

**Comment by GLolol** [comment]
This is equivalent to running `git merge` on various sources. Does anyone have some good candidates?
