### ISSUE TITLE
Branch Size Problems.

### ISSUE THREAD

**Issue by QamarWaqar** [illacceptanything/illacceptanything#555]
Master branch is so huge in size, new devs might be having problems to contribute when some have bandwidth caps. Should have more branches smaller in size. Please comment.
Master branch is is so huge?

**Comment by QamarWaqar** [comment]
Can some one please delete 3 folders in the repository with @ symbol in their name, they add the whole repository in them again and again and hence never ending downloading of the repository, Please fix this asap. Thanx.

**Comment by GLolol** [comment]
Those are submodules, only cloned if you initialize them.

**Comment by GLolol** [comment]
The biggest folders are `illacceptanything` (1.1G) and `linux` (648M), FYI.

**Comment by GLolol** [comment]
Closed by #604.
