### ISSUE TITLE
what popular features should we deprecate

### ISSUE THREAD

**Issue by KelseyDH** [illacceptanything/illacceptanything#561]

**Comment by mikp** [comment]
All!

**Comment by mikp** [comment]
The cat photos!

**Comment by GLolol** [comment]
This one

**Comment by MiLk** [comment]
As your issue doesn't provide enough details, I close it.
Feel free to reopen with more details.

**Comment by KelseyDH** [comment]
We should probably add a deprecation warning before we deprecate my call for deprecations.
