### ISSUE TITLE
Serious issue: Please do *not* accept commits with extremely large files

### ISSUE THREAD

**Issue by KevinNorth** [illacceptanything/illacceptanything#605]
This is a serious issue. I have an actual concern I'd like to address.

I'm having a lot of fun with this repo! When I cloned it onto my own machine, though, it took about 15 minutes to clone. Looking through the repo, I noticed that about 1.5 GB of content was coming from just two top-level directories. One looked like a 1GB iOS app that included several 100+MB images, and the second looks like a clone of a linux distro.

Under the stated rule of "Don't be a d---," I request that you not accept pull requests with extremely large files. Waiting 15 minutes to clone my project really wasn't that bad, and I have more than 1GB to spare, so I'm not upset about the aforementioned files. However, if many people commit 1GB+ files, or someone tries to commit something on the order of 10-100GB+, it could make cloning the project almost impossible, killing all of the fun.

**Comment by KevinNorth** [comment]
See https://github.com/illacceptanything/illacceptanything/issues/555

**Comment by GLolol** [comment]
I have to agree.

**Comment by hhirsch** [comment]
Serious projects should take a long time to clone. Where else should we put the ios app?

**Comment by MiLk** [comment]
https://help.github.com/articles/conditions-for-large-files/

**Comment by GLolol** [comment]
@hhirsch Submodule.

**Comment by ProgVal** [comment]
Could someone rewrite history to remove those huge files?

**Comment by GLolol** [comment]
@ProgVal I've tried, but it ends up freezing my CPU for way too long.

**Comment by GLolol** [comment]
I am going to rewrite the history very soon, replacing it with an initial commit.

Removed folders: `bbb/ linux/ data/random-data`

**Comment by GLolol** [comment]
The repository has been rebased.

**Comment by MiLk** [comment]
:/

**Comment by GLolol** [comment]
@MiLk I don't like deleting content either, but the repo size really needs a limit. I can't even run `git pull` efficiently sometimes without the CPU spiking super high. A `git clone` feels like it'd take days to complete.

**Comment by KevinNorth** [comment]
Thanks for taking care of this issue! :smiley:

**Comment by MiLk** [comment]
Next time: https://help.github.com/articles/remove-sensitive-data/
It's possible to remove large files without loosing the history.

**Comment by initbar** [comment]
:+1:

**Comment by GLolol** [comment]
@MiLk There were literally 90000 commits or whatever for filter-branch to go through. Which would have taken forever to complete...

**Comment by MiLk** [comment]
https://github.com/illacceptanything/illacceptanything/tree/rewrite

**Comment by GLolol** [comment]
:+1:

How long did it take?

**Comment by MiLk** [comment]
~2~3 hours

**Comment by MiLk** [comment]
I will try to cherry pick everything which has been made since the end of my rewritten branch.
If I manage to cherry-pick everything we will be able to swap the master branch.

**Comment by MiLk** [comment]
@illacceptanything/owners I would like to start a vote to replace the current master by https://github.com/illacceptanything/illacceptanything/commits/rewrite
The history has been kept, we shouldn't have lost anything.

The vote will end in 12 hours. (2am UTC / 11am JST / 7pm PDT)
A majority is required to make the replacement.

Until the end of the vote, please don't merge anything.

**Comment by hiiru** [comment]
@MiLk I didn't see this issue before, so I merged a minor change a few minutes ago... (only readme was affected) - I won't merge anything else till the end of the vote

:+1: I agree with the rewrite, seems fine.

**Comment by dbalatero** [comment]
Sounds good to me

**Comment by GLolol** [comment]
Would a squash merge do it? I don't really care, honestly.

**Comment by dbalatero** [comment]
I'll Accept Anything :tm:

**Comment by GLolol** [comment]
:+1: Go ahead and do it!

**Comment by MapleWorld** [comment]
Lol, totally agree, toke forever to clone. First time contributing to open source project don't know how it works, cloned like 15 times, went way over my internet bandwidth.

**Comment by initbar** [comment]
I'll check right now which directory/file is the worst offender.

**Comment by initbar** [comment]
Lol just had a funny idea: change this repo to `illdenyeverything`.

**Comment by GLolol** [comment]
@initbar no

**Comment by initbar** [comment]
suggestion: can we devote `data` to contain type files and ask to link them instead of a fragmented distribution (unless the latter is the target philosophy of this repo)?

For example, we can have:

```
data
|-- [.png]
|-- [.py]
     |-- stuff.py
|-- [.js]
     |-- this\ is\ a\ test.js
     `-- random_stuff.js
labyrinth
|-- enter
etc.
```

And when someone needs to use `random_stuff.js`, they just link them.

**Comment by gnurag** [comment]
+1

**Comment by GLolol** [comment]
Most of the stuff in `data/`  is just random junk people uploaded, lol

**Comment by ProgVal** [comment]
but you deleted the most random of them :(

**Comment by initbar** [comment]
I could do a massive organization pretty easily: should I do the cleanup and make a pull request (I promise not to delete anything)?

**Comment by MiLk** [comment]
Done.

@initbar Please open a PR.

**Comment by GLolol** [comment]
I don't really think more sorting is needed atm... Either way, don't prefix the directory names with a `.` for the extension; that makes them hidden by default, which can be confusing.

**Comment by seyfer** [comment]
It's still sooo big...
