### ISSUE TITLE
Serious Issue: Please take 100% serious. Make all target

### ISSUE THREAD

**Issue by hhirsch** [illacceptanything/illacceptanything#609]
The makefile needs a target to make everything. It should also make the computer go beep. :+1: :v:

**Comment by hhirsch** [comment]
Sorry. Forgot to reference issues. So here you go. 
Todays winners are:
#608 #2 #607

**Comment by hhirsch** [comment]
Needs more cowbell? How awesome are you issue #608? A lot.

**Comment by liamgriffiths** [comment]
:bell: :smiley:

**Comment by MiLk** [comment]
Please open a PR!
