### ISSUE TITLE
Add a Makefile that compiles all .c / .cpp files, etc in code/

### ISSUE THREAD

**Issue by GLolol** [illacceptanything/illacceptanything#651]
There's a lot of cool stuff in this repository, and *making* the *Make*file compile all the compilable things in `code/` would *make* playing with them a lot easier!

Puns very much intended - sue me.

**Comment by GLolol** [comment]
Duplicate of #609 it seems. I feel like this should be closed, however, only *after* the feature is complete.

**Comment by ProgVal** [comment]
Closed by #682.
