### ISSUE TITLE
There is no Hacktoberfest issue tag

### ISSUE THREAD

**Issue by JonnoFTW** [illacceptanything/illacceptanything#778]
Please create the tag so we can submit issues with the tag and win a free t-shirt:

https://hacktoberfest.digitalocean.com/

**Comment by aalind0** [comment]
#778 Create your own label tag while making a pull request. After te tag is created it will automatically be added into your hacktoberfest contributions.

[https://hacktoberfestchecker.herokuapp.com/](url)

**Comment by GLolol** [comment]
Done.
